### ISSUE TITLE
Update UG according to consultation feedback

### ISSUE THREAD

**Issue by fantablack** [AY2122S2-CS2103T-T13-4/tp#113]
# UG Feedback
* ~Change all User to "you"~
* ~Intro can be expanded to explain purposes of MMF better~ (May be expanded upon)
* ~Suggest Clear command upon first use~
* ~Screenshots for Status and Comment~
* ~Specify purposes for commands such as Copy (Why copy?)~
* ~Add warning to clear~
* clearmodules vs deletemodule & addmodule, got extra 's'
* ~suggest how to edit modules under 'Edit'~
* ~change 'flag' to a less technical term~
* ~Screenshots for sort~ (Will add a GIF instead)
* customize header style
* TBA: Order of features TOC

**Comment by bakano98** [comment]
We have no more flags. So I'll just remove `flag` from UG.

**Comment by fantablack** [comment]
* Suggest Clear command upon first use
* Specify purposes for commands such as Copy (Why copy?)
Fixed in #133
