### ISSUE TITLE
GUI Undo/Redo bug

### ISSUE THREAD

**Issue by lawwm** [AY2122S2-CS2103T-T13-4/tp#127]
To replicate, here are the steps:
1. Type `add`
2. Close `AddWindow`
3. Type `undo`

No commands should be undone, and if any action should be taken, it would be to reopen `AddWindow` (but I think this one would be complicated)

Alternatively, if you were to add a new `Person`..
1. Type `add`
2. Fill in details of new `Person`
3. Submit
4. Type undo. It gives the correct behaviour of undoing the adding of a `Person`
5. Type undo again. It gives the wrong behaviour and reports `Undo Success!` when correct one should report `No more commands to undo!`, since typing `add` is just a intermediary to open up `AddWindow` rather than a command that modifies.

**Comment by bakano98** [comment]
Closed by #197
