### ISSUE TITLE
GUI small white box at bottom right corner of panel

### ISSUE THREAD

**Issue by lawwm** [AY2122S2-CS2103T-T13-4/tp#130]
1. List
2. Make the application as small as possible.
3. Notice a small white box at bottom.
4. It disappears when the size of the screen is widened.

**Comment by bakano98** [comment]
Oh I know what's the issue. It's part of the scroll bar, I'll probably fix it another time

**Comment by bakano98** [comment]
Unfortunately, considered a feature flaw and cannot be fixed.
