### ISSUE TITLE
[PE-D] Issue regarding the email and phone number fields' constraints. 

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-4/tp#136]
![image.png](https://raw.githubusercontent.com/blaketingyu/ped/main/files/d303018b-5467-4be1-8262-462da02ca898.png)

![image.png](https://raw.githubusercontent.com/blaketingyu/ped/main/files/98376dc7-f138-4fc6-9a4d-88dbc69b399a.png)

The application allows for very long invalid phone number and emails that are in the wrong format. For example, as long as it consists of @ symbol but does not consist of the ".com" part. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: blaketingyu/ped#2

**Comment by bakano98** [comment]
Valid, update UG as well

**Comment by bakano98** [comment]
Phone number fixed

**Comment by bakano98** [comment]
Email fixed, UG updated

**Comment by bakano98** [comment]
As a note, we can fix this issue by modifying the code because:
1. Omission of constraints on phone number leads to buggy behaviour
2. Omission of certain REGEX checks in email causes buggy behaviour
