### ISSUE TITLE
[PE-D] Images for addmodule and comment in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-4/tp#152]
Not really a bug but just a reminder to include images for these functions in the User Guide :)

(Currently it is mentioned that "See below for an example image" in the User Guide but there are no images found)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Korochii/ped#5

**Comment by bakano98** [comment]
Duplicate to #147 and #144 as they are of similar nature.
