### ISSUE TITLE
[PE-D] Functionality: Unarchive, archive and Undo

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-4/tp#154]
It is documented in the UG that undo does not work for archive and unarchive but archive and unarchive works when undo is performed. However, when archive or unarchive is performed, the user that was archived/unarchived is present in both default and archive pages. 

Expected: Archive and unarchive should not work at all when undo is performed
Actual: when archive or unarchive is performed, the user that was archived/unarchived is present in both default and archive pages. 

![image.png](https://raw.githubusercontent.com/blaketingyu/ped/main/files/24a426ef-97ff-40e1-a384-4ce6ed743e00.png)

![image.png](https://raw.githubusercontent.com/blaketingyu/ped/main/files/4fe4690f-912f-4ef6-a657-2e5a3675e8fd.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: blaketingyu/ped#6

**Comment by bakano98** [comment]
Similar to #151
