### ISSUE TITLE
[PE-D] UI Inconsistency 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T13-4/tp#156]
- When a person is added with very long phone number, the UI shifts to the right, and the comment is not visible on the display

![Screenshot 2022-04-01 at 2.36.05 PM.png](https://raw.githubusercontent.com/goel-a/ped/main/files/4269671d-3685-4092-9b43-74e340b6de49.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: goel-a/ped#3

**Comment by bakano98** [comment]
Limit length of comment
