### ISSUE TITLE
[PE-D] Documentation issue: Maybe include [] for optional fields in add command for comment, status and modules

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-4/tp#179]
![image.png](https://raw.githubusercontent.com/blaketingyu/ped/main/files/a58a1a47-1567-4d1f-aacd-01ef62eb7ace.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: blaketingyu/ped#12

**Comment by bakano98** [comment]
Similar to #180
