### ISSUE TITLE
[PE-D] Missing Commands in Command Summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2103T-T13-4/tp#183]
Great job in ensuring that the command summary is clear, examples are included as well which can be quite useful for users.
However, I noticed that there are some commands that are missing in the summary, such as `exit`, `archive` and `help`.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Korochii/ped#13

**Comment by bakano98** [comment]
Update UG's Command Summary
- Update with all commands
- Command sequence should follow the shortcuts
