### ISSUE TITLE
[PE-D] People with same name

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-4/tp#184]
User Guide does not state that person with same name cannot be added

![image.png](https://raw.githubusercontent.com/redpelican2108/ped/main/files/9f9c427e-fed1-48b8-946c-d41b77d2a860.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: redpelican2108/ped#4

**Comment by bakano98** [comment]
Duplicate to #142
