### ISSUE TITLE
[PE-D] No format for emails given in User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-T13-4/tp#188]
![image.png](https://raw.githubusercontent.com/redpelican2108/ped/main/files/cac89dd9-41fc-4812-ae3f-7bf7c17920ed.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: redpelican2108/ped#8

**Comment by bakano98** [comment]
don't fix
