### ISSUE TITLE
Update Developer's Guide according to feedback received

### ISSUE THREAD

**Issue by bakano98** [AY2122S2-CS2103T-T13-4/tp#97]
In general, DG is quite unorganised

- Have an introduction
- ~Update value proposition~ (Ben)
- Put more 2101 sass
- ~Use case summary at start of dg~ (Ben, for now its at beginning of use case section)
- ~Update AB3 stuff to adapt to our app~ (Bryan)
- Improve formatting for text-heavy sections
- Can split implementation details into steps to make it more palatable 
- ~Case 1 and Case 2 of Add Modules is similar — need to fix~ (Bryan)
- No need to talk about returning stuff in implementation details
- Can try to improve visual hiearchy/clarity
- ~Design considerations: put current implementation as first option~ (Ben/ Wei Ming)
- ~Within each pros and cons, change to a numbered list~ (Ben/ Wei Ming)
- A lot of text? try to cut down (Not complete yet, added white space only)

Aim to start doing now, finish by mid-v1.4

**Comment by bakano98** [comment]
@lawwm @fantablack @Btaykb @junlee1991 
Similarly, just put a comment on what you are/will be doing so we know.

**Comment by Btaykb** [comment]
Going to work on Use case summary at start of DG, Put current implementation as first option, Within each pros and cons change to a numbered list, try to cut down on text (or at least try to use whitespace to make it more readable)

**Comment by fantablack** [comment]
* Update AB3 stuff to adapt to our app (ModelClassDiagrams)
* Case 1 and Case 2 of Add Modules is similar — need to fix

Fixed these in PR #107
